exclude: data
default_stages: [commit, push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-docstring-first
    - id: check-added-large-files
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    args: ['--config=pyproject.toml']
    language_version: python3
    exclude: ^(docs)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      # https://github.com/pre-commit/pre-commit-hooks/issues/112
      args: ['--config=setup.cfg']
      exclude: ^(docs)
- repo: https://github.com/econchick/interrogate
  rev: 1.4.0
  hooks:
    - id: interrogate
      args: ['--config=pyproject.toml']
      # exclude should be kept separate from config file when using pre-commit
      exclude: ^(docs|setup.py)
- repo: https://github.com/pycqa/isort
  rev: 5.9.3
  hooks:
  - id: isort
    additional_dependencies: ['toml']
    exclude: ^(docs)
